---
title: "New MU Comparison Report"
author: "Andrew Gene Brown"
date: "3/10/2020"
output: html_document
---

```{r setup}
knitr::opts_chunk$set(echo = FALSE, message=FALSE)

library(plyr)
library(rgdal)
library(sharpshootR)

source('nu-config.R')
source('sampleRasterStackByMUNew.R')

# convenience variables from raster.list
raster.type <- lapply(raster.list, function(l) return(l$type))
raster.files <- lapply(raster.list, function(l) return(l$file))
raster.pnames <- lapply(raster.list, function(l) return(l$name))
raster.labels <- lapply(raster.list, function(l) return(l$label))

mu <- try(readOGR(dsn=mu.dsn, layer=mu.layer, stringsAsFactors = FALSE))
if(class(mu) == 'try-error')
  stop(paste0('Cannot read map unit polygon/feature file: "', mu.dsn, ' / ', mu.layer, '"'), call. = FALSE)
if(!(mu.col %in% names(mu)))
  stop(paste0('Cannot find map unit column (',mu.col,') in attribute table of: "', mu.dsn, ' / ', mu.layer,'"'), call. = FALSE)

accessible.inputs <- file.access(as.character(unlist(raster.files)), mode = 4) + 1 
if(any( accessible.inputs == 0 )) {
  unreadable.files <- names(which(accessible.inputs == 0))
  stop(paste0("The following input files either do not exist or are unreadable: \n", paste0(unreadable.files, collapse=", ")))
}

if(exists('mu.set')) { 
  mu.set <- as.character(mu.set)
  mu.set.bak <- mu.set
  mu_nosp <- !(mu.set %in% mu[[mu.col]])
  
  # check if any of the predefined musyms are absent from the spatial
  if(any(mu_nosp))
    mu.set <- mu.set[-which(mu_nosp)] #if so, remove them
  
  # if we removed everything (e.g. no musyms match due to wrong config file?), fail gracefully
  if(length(mu.set) == 0) 
    stop(paste0("Cannot find map unit polygons with symbol: ",paste0(mu.set.bak,collapse=", ")))
  
  # if mu.set defined in config.R, only keep the features with musym matching set
  mu <- mu[which(mu[[mu.col]] %in% mu.set), ] 
} else {
  # if mu.set is not predefined, ordering is determined by the order of musyms in the source file
  mu.set <- sort(unique(mu[[mu.col]]))
}

if(!dir.exists('output')) 
  dir.create('./output')

if(!exists('shp.unsampled.fname')) shp.unsampled.fname <- paste0('un-sampled-', paste(mu.set, collapse='_'))
if(!exists('shp.stats.fname')) shp.stats.fname <- paste0('polygons-with-stats-', paste(mu.set, collapse='_'))
if(!exists('shp.qc.fname')) shp.qc.fname <- paste0('poly-qc-', paste(mu.set, collapse='_'))

if(!exists('csv.qc.fname')) csv.qc.fname <- paste0('poly-qc-', paste(mu.set, collapse='_'),'.csv')
if(!exists('csv.stats.fname')) csv.stats.fname <- paste0('poly-stats-', paste(mu.set, collapse='_'), '.csv')

outputfiles <- c(paste0(c(shp.unsampled.fname,shp.stats.fname,shp.qc.fname),".shp"), csv.qc.fname, csv.stats.fname)
if(any(grepl(basename(outputfiles), pattern='([/\\|<>:\\*?\"])'))) {
  stop("Map unit set or output file name contains invalid characters for filename. Either override default output filenames in config.R or remove [/\\|<>:\\*?\"] characters from your map unit symbols.", call. = FALSE)
}

# in order to avoid column name collisions due to DBF limitations, keep only the mu.col column
mu <- mu[, mu.col, drop=FALSE]

# add a unique polygon ID
mu$pID <- seq(from=1, to=length(mu))

if(cache.samples & file.exists('cached-samples.Rda')) {
  message('Using cached raster samples...')
  .sampling.time <- 'using cached samples'
  load('cached-samples.Rda')
} else {
  .timer.start <- Sys.time()
    sampling.res <- suppressWarnings(sampleRasterStackByMUNew(mu, 
                                                         mu.set, 
                                                         mu.col, 
                                                         raster.list, 
                                                         pts.per.acre, 
                                                         estimateEffectiveSampleSize = correct.sample.size))
  .timer.stop <- Sys.time()
  
  .sampling.time <- format(difftime(.timer.stop, .timer.start, units='mins'), digits=2)
  
  print(paste0("Completed sampling of raster stack for poly symbols (",
               paste(mu.set,collapse=","),") in ",.sampling.time,"."))
  
  #sampling.res$raster.samples$.id <- factor(sampling.res$raster.samples$.id, levels=mu.set)
  
  print("DONE!")
  
  if(cache.samples)
    save(mu, sampling.res,file = 'cached-samples.Rda')
}
```

```{r echo=FALSE}
# handy function to replace plyr 
list.to.df <- function(l, idcol) {
  l.names <- names(l)
  n.l <- unlist(lapply(l, nrow))
  res <- as.data.frame(do.call('rbind', l))
  buf <- list()
  for(i in 1:length(l.names)) {
    if(length(n.l[i]))
      if(n.l[i] > 0)
        buf <- c(buf, rep(l.names[i], n.l[i]))
  }
  res[[idcol]] <- unlist(buf)
  rownames(res) <- NULL
  return(res)
}

summarizeSamples <- function(samples, probs=c(0,0.05,0.5,0.95,1))  {
  res <- lapply(raster.pnames, function(n) {
    n.obs <- c(sum(!is.na(samples[, n])), length(samples[,n]))
    names(n.obs) <- c("non.na", "n.obs")
    return(c(quantile(samples[, n], probs=probs, na.rm=TRUE), n.obs))
  })
  names(res) <- raster.pnames
  res <- list.to.df(res, idcol='variable')
  return(res)
}

getThresholds <- function(mus, varname) {
  if(length(varname) > 1) {
    varname <- varname[1]
    message("Multiple variable names supplied to getThresholds(), returning values for first name.")
  }
  
  res.max <- rep(Inf, length(mus))
  res.min <- rep(-Inf, length(mus))
  
  for(tl in threshold.list) {
    if(tl$name == varname & all(grepl(tl$pattern, mus))) {
      print(paste(unique(mus), varname, tl$name, tl$pattern))
      res.max <- rep(tl$vmax, length(mus))
      res.min <- rep(tl$vmin, length(mus))
    }
  }      
  
  return(data.frame(vmin=res.min,
                    vmax=res.max))
}

thresholdSamples <- function(samples)  {
  res <- lapply(raster.pnames, function(n) {
    foo <- factor(rep("IN", nrow(samples)), levels=c("LT","IN","GT"))
    tthresh <- quantile(samples[,n], probs=c(0.01,0.99), na.rm=T)
    #thresh <- list()
    #thresh$vmin <- tthresh[1]
    #thresh$vmax <- tthresh[2]
    thresh <- getThresholds(samples[,1], varname = n)
    foo[samples[, n] > thresh$vmax] <- "GT"
    foo[samples[, n] < thresh$vmin] <- "LT"
    tab <- t(table(foo))
    names(tab) <- c("LT","IN","GT")
    return(as.data.frame(t(c(tab, unique(thresh)))))
  })
  names(res) <- raster.pnames
  res <- list.to.df(res, idcol='variable')
  return(res)
}
```

```{r}
# example thresholding BY MU
samples.by.mu <- split(sampling.res$raster.samples,
                      sampling.res$raster.samples[[mu.col]])
res2 <- list.to.df(lapply(samples.by.mu, thresholdSamples), mu.col)
res2 <- res2[order(res2$musym, res2$variable),]
knitr::kable(res2, row.names = FALSE)

# example thresholding BY POLYGON
samples.by.poly <- split(sampling.res$raster.samples,
                      sampling.res$raster.samples[["pID"]])
res3 <- list.to.df(lapply(samples.by.poly, thresholdSamples), "pID")
res3 <- res3[order(res3$pID, res3$variable),]
knitr::kable(res3, row.names = FALSE)
```
